/**
 * ⚠️  DEVELOPMENT / DEMO DATA — NOT REAL CAFÉS  ⚠️
 *
 * Every café below is invented. The names are fictional, the ratings were
 * written by hand to exercise the UI, and the notes are illustrative examples
 * rather than quotes from real people who visited a real place.
 *
 * This exists so the app is usable before real contributions arrive. It is
 * marked `source: "seed"` throughout, and the interface renders a persistent
 * "Demo data" badge wherever seed records appear. When real data lands, seed
 * data is deleted rather than quietly blended in. See docs/PLAN.md §16.
 *
 * Coordinates are placed in real neighbourhoods so that search, distance and
 * map behaviour can be exercised realistically. The neighbourhoods are real;
 * the cafés in them are not.
 */

export interface SeedReport {
  readonly wifi?: number;
  readonly outlets?: number;
  readonly seating?: number;
  readonly longStay?: number;
  readonly noise?: number;
  readonly allowsCalls?: boolean;
  readonly hasAirConditioning?: boolean;
  readonly hasRestroom?: boolean;
  readonly comment?: string;
  readonly daysAgo: number;
}

export interface SeedCafe {
  readonly slug: string;
  readonly name: string;
  readonly description: string;
  readonly latitude: number;
  readonly longitude: number;
  readonly address: string;
  readonly neighborhood: string;
  readonly city: string;
  readonly countryCode: string;
  readonly openingHours: string | null;
  readonly website: string | null;
  readonly reports: readonly SeedReport[];
}

export const SEED_CAFES: readonly SeedCafe[] = [
  {
    slug: "estudio-bica-vila-mariana",
    name: "Estúdio Bica",
    description:
      "A converted ground-floor apartment with long shared tables and a lot of natural light.",
    latitude: -23.5892,
    longitude: -46.6354,
    address: "Rua Dr. Diogo de Faria, 700",
    neighborhood: "Vila Mariana",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Fr 08:00-19:00; Sa 09:00-16:00",
    website: null,
    reports: [
      {
        wifi: 5,
        outlets: 5,
        seating: 5,
        longStay: 5,
        noise: 4,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        comment:
          "The long table at the back has sockets along its whole length. Nobody minds if you stay all afternoon.",
        daysAgo: 6,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 4,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 18,
      },
      {
        wifi: 4,
        outlets: 5,
        seating: 4,
        longStay: 5,
        noise: 3,
        allowsCalls: true,
        hasRestroom: true,
        comment: "Gets busier around lunch, but people still work through it.",
        daysAgo: 27,
      },
      {
        wifi: 5,
        outlets: 5,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 41,
      },
      {
        wifi: 4,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 4,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 63,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 3,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 90,
      },
    ],
  },
  {
    slug: "cafe-hipotenusa-vila-mariana",
    name: "Café Hipotenusa",
    description: "Small corner café with a handful of two-person tables and a quiet back room.",
    latitude: -23.5871,
    longitude: -46.6389,
    address: "Rua Domingos de Morais, 1420",
    neighborhood: "Vila Mariana",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Sa 07:30-20:00; Su 09:00-14:00",
    website: null,
    reports: [
      {
        wifi: 3,
        outlets: 2,
        seating: 3,
        longStay: 4,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        comment:
          "Genuinely quiet in the back room. Only two sockets though, and both get taken early.",
        daysAgo: 11,
      },
      {
        wifi: 3,
        outlets: 2,
        seating: 3,
        longStay: 4,
        noise: 5,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 34,
      },
      {
        wifi: 4,
        outlets: 1,
        seating: 3,
        longStay: 3,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        comment: "Perfect if you only need a couple of hours and your battery is full.",
        daysAgo: 52,
      },
      {
        wifi: 3,
        outlets: 2,
        seating: 2,
        longStay: 4,
        noise: 5,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 78,
      },
      {
        wifi: 3,
        outlets: 2,
        seating: 3,
        longStay: 4,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        daysAgo: 120,
      },
    ],
  },
  {
    slug: "torrefacao-meridiano-pinheiros",
    name: "Torrefação Meridiano",
    description: "Roastery and café. Loud grinder, excellent coffee, mixed fortunes for working.",
    latitude: -23.5648,
    longitude: -46.6823,
    address: "Rua dos Pinheiros, 380",
    neighborhood: "Pinheiros",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Tu-Su 08:00-18:00",
    website: null,
    reports: [
      {
        wifi: 4,
        outlets: 3,
        seating: 4,
        longStay: 3,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        comment: "The roaster runs most mornings and it is genuinely loud. Afternoons are calmer.",
        daysAgo: 4,
      },
      {
        wifi: 4,
        outlets: 3,
        seating: 4,
        longStay: 3,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 22,
      },
      {
        wifi: 5,
        outlets: 2,
        seating: 4,
        longStay: 2,
        noise: 3,
        allowsCalls: true,
        hasRestroom: true,
        comment: "Asked politely to free the table at 13:00 on a Saturday.",
        daysAgo: 45,
      },
      {
        wifi: 4,
        outlets: 3,
        seating: 3,
        longStay: 3,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 70,
      },
      {
        wifi: 4,
        outlets: 4,
        seating: 4,
        longStay: 3,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 96,
      },
      {
        wifi: 3,
        outlets: 3,
        seating: 4,
        longStay: 3,
        noise: 3,
        allowsCalls: true,
        hasRestroom: true,
        daysAgo: 130,
      },
    ],
  },
  {
    slug: "sala-de-leitura-pinheiros",
    name: "Sala de Leitura",
    description:
      "Bookshop café where the upstairs floor is kept deliberately quiet. No calls, by house rule.",
    latitude: -23.5612,
    longitude: -46.6871,
    address: "Rua Artur de Azevedo, 210",
    neighborhood: "Pinheiros",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Fr 09:00-21:00; Sa-Su 10:00-19:00",
    website: null,
    reports: [
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        comment:
          "Upstairs is close to silent and there is a sign asking people to take calls outside. Ideal for deep work, useless for meetings.",
        daysAgo: 3,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 15,
      },
      {
        wifi: 4,
        outlets: 5,
        seating: 5,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 29,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 4,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 44,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 58,
      },
      {
        wifi: 4,
        outlets: 4,
        seating: 5,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 81,
      },
      {
        wifi: 5,
        outlets: 3,
        seating: 5,
        longStay: 5,
        noise: 5,
        allowsCalls: false,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 110,
      },
    ],
  },
  {
    slug: "padaria-do-angulo-vila-madalena",
    name: "Padaria do Ângulo",
    description:
      "Traditional bakery with a few marble tables. Busy, bright, and not built for laptops.",
    latitude: -23.5539,
    longitude: -46.6902,
    address: "Rua Aspicuelta, 55",
    neighborhood: "Vila Madalena",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Su 06:00-20:00",
    website: null,
    reports: [
      {
        wifi: 2,
        outlets: 1,
        seating: 2,
        longStay: 2,
        noise: 1,
        allowsCalls: true,
        hasAirConditioning: false,
        hasRestroom: true,
        comment: "Great pão de queijo, but the tables are tiny and it never stops being busy.",
        daysAgo: 9,
      },
      {
        wifi: 2,
        outlets: 1,
        seating: 2,
        longStay: 2,
        noise: 1,
        allowsCalls: true,
        hasRestroom: true,
        daysAgo: 26,
      },
      {
        wifi: 1,
        outlets: 1,
        seating: 2,
        longStay: 1,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: false,
        hasRestroom: true,
        comment:
          "Tried to work here for an hour and gave up. Listed so nobody else makes the trip.",
        daysAgo: 55,
      },
      {
        wifi: 2,
        outlets: 2,
        seating: 1,
        longStay: 2,
        noise: 1,
        allowsCalls: true,
        hasRestroom: true,
        daysAgo: 88,
      },
    ],
  },
  {
    slug: "quintal-tipografia-vila-madalena",
    name: "Quintal Tipografia",
    description: "Courtyard café behind a print shop. Covered outdoor seating, patchy signal.",
    latitude: -23.5566,
    longitude: -46.6934,
    address: "Rua Harmonia, 890",
    neighborhood: "Vila Madalena",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "We-Su 10:00-19:00",
    website: null,
    reports: [
      {
        wifi: 3,
        outlets: 3,
        seating: 4,
        longStay: 5,
        noise: 4,
        allowsCalls: true,
        hasAirConditioning: false,
        hasRestroom: true,
        comment: "Lovely to sit in. Wi-Fi drops in the courtyard, so sit near the doorway.",
        daysAgo: 13,
      },
      {
        wifi: 2,
        outlets: 3,
        seating: 4,
        longStay: 5,
        noise: 4,
        allowsCalls: true,
        hasRestroom: true,
        daysAgo: 37,
      },
      {
        wifi: 3,
        outlets: 2,
        seating: 4,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: false,
        hasRestroom: true,
        daysAgo: 66,
      },
    ],
  },
  {
    slug: "mezanino-consolacao",
    name: "Mezanino Café",
    description: "First-floor café above a stationery shop, with a mezzanine of proper desks.",
    latitude: -23.5548,
    longitude: -46.6612,
    address: "Rua Augusta, 1500",
    neighborhood: "Consolação",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Fr 08:00-22:00; Sa 10:00-18:00",
    website: null,
    reports: [
      {
        wifi: 5,
        outlets: 5,
        seating: 5,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        comment: "Actual desks with actual chairs. Fills up after 18:00 with students.",
        daysAgo: 5,
      },
      {
        wifi: 5,
        outlets: 5,
        seating: 5,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 20,
      },
      {
        wifi: 4,
        outlets: 5,
        seating: 5,
        longStay: 4,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 33,
      },
      {
        wifi: 5,
        outlets: 4,
        seating: 5,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasRestroom: true,
        daysAgo: 49,
      },
      {
        wifi: 5,
        outlets: 5,
        seating: 4,
        longStay: 3,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 72,
      },
    ],
  },
  {
    slug: "balcao-nove-itaim-bibi",
    name: "Balcão Nove",
    description:
      "Counter-service café aimed at the office crowd. Fast, functional, not for lingering.",
    latitude: -23.5853,
    longitude: -46.6791,
    address: "Rua Joaquim Floriano, 300",
    neighborhood: "Itaim Bibi",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Mo-Fr 07:00-18:00",
    website: null,
    reports: [
      {
        wifi: 4,
        outlets: 2,
        seating: 2,
        longStay: 1,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: false,
        comment: "Signs asking for a 45-minute limit at peak times, and they mean it.",
        daysAgo: 8,
      },
      {
        wifi: 4,
        outlets: 2,
        seating: 2,
        longStay: 1,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: false,
        daysAgo: 31,
      },
      {
        wifi: 5,
        outlets: 1,
        seating: 2,
        longStay: 2,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        daysAgo: 60,
      },
    ],
  },
  {
    slug: "casa-vagalume-perdizes",
    name: "Casa Vagalume",
    description: "Quiet house-café on a residential street. Regulars stay for hours.",
    latitude: -23.5372,
    longitude: -46.6795,
    address: "Rua Cardoso de Almeida, 1100",
    neighborhood: "Perdizes",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: "Tu-Sa 09:00-19:00",
    website: null,
    reports: [
      {
        wifi: 4,
        outlets: 4,
        seating: 4,
        longStay: 5,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        comment: "Feels like working from a friend's living room. Nobody is counting the hours.",
        daysAgo: 16,
      },
      {
        wifi: 4,
        outlets: 4,
        seating: 4,
        longStay: 5,
        noise: 4,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 40,
      },
    ],
  },
  {
    slug: "esquina-do-tempo-santa-cecilia",
    name: "Esquina do Tempo",
    description: "Corner café that has only just opened. Very little is known about it yet.",
    latitude: -23.5372,
    longitude: -46.6595,
    address: "Rua Jaguaribe, 40",
    neighborhood: "Santa Cecília",
    city: "São Paulo",
    countryCode: "BR",
    openingHours: null,
    website: null,
    reports: [
      {
        wifi: 5,
        outlets: 4,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: true,
        hasRestroom: true,
        comment:
          "First visit and it looked promising, but one opinion is not much to go on — please add yours.",
        daysAgo: 2,
      },
    ],
  },
  {
    slug: "atlantico-lento-copacabana",
    name: "Atlântico Lento",
    description: "Sea-facing café two blocks from the beach, popular with people working remotely.",
    latitude: -22.9711,
    longitude: -43.1822,
    address: "Rua Barata Ribeiro, 500",
    neighborhood: "Copacabana",
    city: "Rio de Janeiro",
    countryCode: "BR",
    openingHours: "Mo-Su 07:00-20:00",
    website: null,
    reports: [
      {
        wifi: 4,
        outlets: 3,
        seating: 4,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        comment:
          "Busy but tolerant. Air conditioning matters here more than anywhere else on this list.",
        daysAgo: 12,
      },
      {
        wifi: 3,
        outlets: 3,
        seating: 4,
        longStay: 4,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 38,
      },
      {
        wifi: 4,
        outlets: 4,
        seating: 3,
        longStay: 4,
        noise: 2,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 67,
      },
      {
        wifi: 4,
        outlets: 3,
        seating: 4,
        longStay: 5,
        noise: 3,
        allowsCalls: true,
        hasAirConditioning: true,
        hasRestroom: true,
        daysAgo: 94,
      },
    ],
  },
  {
    slug: "tipografia-do-bairro-alto-lisboa",
    name: "Tipografia do Bairro",
    description: "Narrow two-floor café. Upstairs has four tables and a view over the street.",
    latitude: 38.7156,
    longitude: -9.1449,
    address: "Rua da Rosa, 180",
    neighborhood: "Bairro Alto",
    city: "Lisbon",
    countryCode: "PT",
    openingHours: "Mo-Sa 08:30-19:00",
    website: null,
    reports: [
      {
        wifi: 5,
        outlets: 3,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        comment: "Upstairs is calm on weekday mornings. Sockets only along the window wall.",
        daysAgo: 7,
      },
      {
        wifi: 5,
        outlets: 3,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 25,
      },
      {
        wifi: 4,
        outlets: 2,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        daysAgo: 51,
      },
      {
        wifi: 5,
        outlets: 3,
        seating: 3,
        longStay: 3,
        noise: 3,
        allowsCalls: false,
        hasRestroom: true,
        daysAgo: 83,
      },
      {
        wifi: 5,
        outlets: 3,
        seating: 4,
        longStay: 4,
        noise: 4,
        allowsCalls: false,
        hasAirConditioning: false,
        hasRestroom: true,
        daysAgo: 105,
      },
    ],
  },
] as const;
